In [1]:
import requests
import json
import pandas as pd
from config2 import api_key
from config2 import gkey
import csv
import gmaps

In [2]:
gmaps.configure(api_key=gkey)

In [3]:
beer_csv = pd.read_csv("addresses2.csv", delimiter=",")
beer_csv_df=pd.DataFrame(beer_csv)
beer_csv_df.head(1)

,Name,Address,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,City
0,10 Barrel Brewing Co.,1501 E St,San Diego,CA 92101,NaN,NaN,San Diego

In [4]:
top_5_csv = pd.read_csv("top_5_info.csv", delimiter=",")
top_5_csv_df=pd.DataFrame(top_5_csv)
top_5_csv_df.head()

                      name                  address          city  medal count
0      Pizza Port Carlsbad  571 Carlsbad Village Dr      Carlsbad           24
1     AleSmith Brewing Co.         9990 AleSmith Ct     San Diego           10
2           The Lost Abbey             155 Mata Way    San Marcos            9
3  Pizza Port Solana Beach             35 N Hwy 101  Solana Beach            8
4   Pizza Port Ocean Beach             956 Bacon St     San Diego            7

In [5]:
top_5 = list(zip(top_5_csv_df["name"], top_5_csv_df["medal count"]))
top5 = top_5_csv_df
top5.head(1)

                  name                  address      city  medal count
0  Pizza Port Carlsbad  571 Carlsbad Village Dr  Carlsbad           24

In [6]:
biz_name = beer_csv_df["Name"]
addr = beer_csv_df["Address"]
city = beer_csv_df["City"]
addy = addr.values.tolist()
biz = biz_name.values.tolist()
cities = city.values.tolist()
len(cities)

152

In [7]:
# for index, row in beer_csv_df.iterrows():
#     biz, addy = row['Name'], row['Address']
#     print(a)

In [8]:
ids = []
name = []
address = []
lat = []
lng = []
rating = []
review = []
phone = []
citi = []
x = -1
addy 
biz

skippedb = []
skippeda = []
for b, a, c in zip(biz, addy, cities):
    x += 1
    print(f"printing {b} || {x} of {len(biz)} ")
# for b, a, in beer_csv_df.iterrows():
    headers = {'Authorization': 'Bearer %s' % api_key}
    params = {'name':b,'address1':a,'city':c, 'state':'Ca', 'country':'US'}
    url = "https://api.yelp.com/v3/businesses/matches"
    try:
        response = requests.get(url, headers=headers, params=params)
        response_json = response.json()
        response_json
        idz = response_json["businesses"][0]["id"]
        addresses = response_json["businesses"][0]["location"]["address1"]
        lats = response_json["businesses"][0]["coordinates"]["latitude"]
        lngs = response_json["businesses"][0]["coordinates"]["longitude"]
        names = response_json["businesses"][0]["name"]
        name.append(names)
        address.append(addresses)
        lat.append(lats)
        lng.append(lngs)
        ids.append(idz)
    except:
        skippedb.append(b)
        skippeda.append(a)
        print('Skipping:', b)
        continue

for b, a, c, i, in zip(biz, addy, cities, ids):
    params = {'name':b,'address1':a,'city':c, 'state':'Ca', 'country':'US'}
    url = "https://api.yelp.com/v3/businesses/"
    response = requests.get(url + i, headers=headers, params=params)
    response_json = response.json()
    ratings = response_json["rating"]
    reviews = response_json["review_count"]
    phones = response_json["display_phone"]
    cit = response_json["location"]["city"]
    citi.append(cit)
    phone.append(phones)
    review.append(reviews)
    rating.append(ratings)

printing 10 Barrel Brewing Co. || 0 of 152
printing 2Kids Brewing Co. || 1 of 152
printing 13 Point Brewing Company || 2 of 152
printing 32 North Brewing Co. || 3 of 152
printing Abnormal Beer Company || 4 of 152
printing AleSmith Brewing Company || 5 of 152
printing Align Brewing Co. || 6 of 152
printing Alpine Beer Company || 7 of 152
printing Amplified Ale Works || 8 of 152
printing Amplified Ale Works || 9 of 152
printing Arcana Brewing Co. || 10 of 152
printing Attitude Brewing || 11 of 152
printing Automatic Brewing Company || 12 of 152
printing Aztec Brewing Company || 13 of 152
printing Back Street Brewery || 14 of 152
printing Bagby Beer Comapny || 15 of 152
printing Ballast Point Brewing & Spirits - Home Brew Mart || 16 of 152
printing Ballast Point Brewing & Spirits - Little Italy || 17 of 152
printing Ballast Point Brewing & Spirits - Miramar || 18 of 152
printing Ballast Point Brewing & Spirits - Scripps Ranch || 19 of 152
printing Barn Brewery || 20 of 152
printing Barrel Harbor || 21 of 152
printing Battlemage Brewing Company || 22 of 152
printing Bay Bridge Brewing || 23 of 152
printing Bay City Brewing || 24 of 152
printing Beach Grease Beer Co. || 25 of 152
printing Bear Roots Brewing Co. || 26 of 152
printing Belching Beaver Brewery || 27 of 152
printing Belching Beaver Brewery || 28 of 152
printing Belching Beaver Brewery Tavern & Grill || 29 of 152
printing Benchmark Brewing || 30 of 152
printing Bitter Brothers Brewing || 31 of 152
printing Black Plague Brewing || 32 of 152
printing BNS Brewing & Distilling || 33 of 152
printing Bolt Brewing Co. || 34 of 152
printing Booze Brothers Brewing Co. || 35 of 152
printing Border X Brewing || 36 of 152
printing Breakwater Brewing Company || 37 of 152
printing Burgeon Beer Company || 38 of 152
printing Burning Beard Brewing Company || 39 of 152
printing California Wild Ales || 40 of 152
printing Chula Vista Brewery || 41 of 152
printing Circle 9 Brewing || 42 of 152
printing Coronado Brewing Company || 43 of 152
printing Coronado Brewing Company || 44 of 152
printing Creative Creature Brewing || 45 of 152
printing Culture Brewing Co. || 46 of 152
printing Culver Beer Co. || 47 of 152
printing Deft Brewing || 48 of 152
printing Division 23 Brewing || 49 of 152
printing Dos Desperados Brewery || 50 of 152
printing Double Peak Brewing || 51 of 152
printing Duck Foot Brewing Co. || 52 of 152
printing Ebullition Brew Works || 53 of 152
printing Embarcadero Brewing Company || 54 of 152
printing Eppig Brewing || 55 of 152
printing Escondido Brewing Company || 56 of 152
printing Fall Brewing Co. || 57 of 152
printing Fourpenny House || 58 of 152
printing Gordon Biersch Brewery Restaurant || 59 of 152
printing Green Flash Brewing Co. || 60 of 152
printing Groundswell Brewing Co. || 61 of 152
printing Groundswell Brewing Co. || 62 of 152
printing Guadalupe Brewery || 63 of 152
printing Half Door Brewing Co. || 64 of 152
printing Helia Brewing || 65 of 152
printing Helix Brewing Co. || 66 of 152
printing Helm's Brewing || 67 of 152
printing Hillcrest Brewing Company || 68 of 152
printing Hodad's Brewing Co. || 69 of 152
Skipping: Hodad's Brewing Co.
printing Home Brewing Co || 70 of 152
Skipping: Home Brewing Co
printing Horus Aged Ales || 71 of 152
printing Indian Joe Brewing || 72 of 152
printing Iron Fist Brewing Company || 73 of 152
printing Jacked Up Brewing || 74 of 152
printing Jamul Brewing Co. || 75 of 152
Skipping: Jamul Brewing Co.
printing Julian Beer Co. || 76 of 152
printing Karl Strauss || 77 of 152
printing Karl Strauss 4S Ranch || 78 of 152
printing Karl Strauss Carlsbad || 79 of 152
printing Karl Strauss Downtown || 80 of 152
printing Karl Strauss La Jolla || 81 of 152
printing Karl Strauss Sorrento Mesa || 82 of 152
printing Kensington Brewing Company || 83 of 152
Skipping: Kensington Brewing Company
printing Ketch Brewing || 84 of 152
printing Kilowatt Brewing Company || 85 of 152
printing KnB Brewery || 86 of 152
printing Knotty Brewing Co. || 87 of 152
printing Latitude 33 Brewing Company || 88 of 152
printing Legacy Brewing Company || 89 of 152
printing Lightning Brewery || 90 of 152
printing Little Miss Brewing || 91 of 152
printing Longship Brewery || 92 of 152
printing Mason Ale Works || 93 of 152
printing Mason Ale Works || 94 of 152
Skipping: Mason Ale Works
printing Melvin Brewing Co. || 95 of 152
printing Midnight Jack Brewing Company || 96 of 152
printing Mike Hess Brewing || 97 of 152
printing Mikkeller Brewing San Diego || 98 of 152
printing Mission Brewery || 99 of 152
printing Modern Times || 100 of 152
printing Mother Earth Brew Company || 101 of 152
Skipping: Mother Earth Brew Company
printing New English Brewing Company || 102 of 152
printing Nickel Beer Company || 103 of 152
printing North Park Beer Co || 104 of 152
printing Northern Pine Brewing Company || 105 of 152
printing Novo Brazil Brewing Co. || 106 of 152
printing OB Brewery || 107 of 152
printing Oceanside Brewing Company || 108 of 152
printing Oggi's Carmel Mountain Ranch || 109 of 152
printing Pacific Beach Ale House || 110 of 152
printing Pacific Islander Beer Co. || 111 of 152
printing Papa Marce's Cerveceria || 112 of 152
printing Pariah Brewing Company || 113 of 152
printing Pizza Port Bressi Ranch || 114 of 152
printing Pizza Port Carlsbad || 115 of 152
printing Pizza Port Ocean Beach || 116 of 152
printing Pizza Port Solana Beach || 117 of 152
printing Plan 9 Ale House || 118 of 152
printing Poor House Brewing Co || 119 of 152
printing Port Brewing / The Lost Abbey || 120 of 152
printing Prohibition Brewing Company || 121 of 152
printing Protector Brewery || 122 of 152
printing Pure Project Brewing || 123 of 152
printing Quantum Brewing Co. || 124 of 152
printing Reckless Brewing Co. || 125 of 152
printing Resident Brewing Co. || 126 of 152
Skipping: Resident Brewing Co.
printing Rip Current Brewing Co. || 127 of 152
printing Rock Bottom Brewery Restaurant La Jolla || 128 of 152
printing Rough Draft Brewing Company || 129 of 152
printing Rouleur Brewing Company || 130 of 152
printing San Diego Brewing Company || 131 of 152
printing San Marcos Brewery & Grill || 132 of 152
printing Savagewood Brewing || 133 of 152
printing Second Chance Beer Co. || 134 of 152
printing Smoking Cannon Brewery || 135 of 152
printing Societe Brewing Co. || 136 of 152
printing South Park Brewing Co. || 137 of 152
printing SR76 Brewery || 138 of 152
printing St. Archer Brewing Co. || 139 of 152
printing Stone Brewing Company || 140 of 152
printing Stone Brewing World Bistro and Gardens Liberty Station || 141 of 152
printing Stumblefoot Brewing Company || 142 of 152
printing The Bell Marker || 143 of 152
printing Thorn Brewing - North Park || 144 of 152
printing Thorn Brewing - Barrio Logan || 145 of 152
printing Thr3e Punks Ales Brewing Co. || 146 of 152
printing Thunderhawk Alements || 147 of 152
printing Viewpoint Brewing Co. || 148 of 152
printing Wavelength Brewing Co. || 149 of 152
printing White Labs || 150 of 152
printing Wild Barrel Brewing || 151 of 152

In [10]:
t5_ids = []
t5_name = []
t5_address = []
t5_lat = []
t5_lng = []
t5_rating = []
t5_review = []
t5_phone = []
t5_citi = []
x = -1

for b, a, c in list(zip(top5["name"], top5["address"], top5["city"])):
    x += 1
    print(f"printing {b} || {x} of {len(biz)} ")
# for b, a, in beer_csv_df.iterrows():
    headers = {'Authorization': 'Bearer %s' % api_key}
    params = {'name':b,'address1':a,'city':c, 'state':'Ca', 'country':'US'}
    url = "https://api.yelp.com/v3/businesses/matches"
    try:
        response = requests.get(url, headers=headers, params=params)
        response_json = response.json()
        response_json
        idz = response_json["businesses"][0]["id"]
        addresses = response_json["businesses"][0]["location"]["address1"]
        lats = response_json["businesses"][0]["coordinates"]["latitude"]
        lngs = response_json["businesses"][0]["coordinates"]["longitude"]
        names = response_json["businesses"][0]["name"]
        t5_ids.append(idz)
        t5_name.append(names)
        t5_address.append(addresses)
        t5_lat.append(lats)
        t5_lng.append(lngs)
    except:
        continue
        
for b, a, c, i, in list(zip(top5["name"], top5["address"], top5["city"], t5_ids)):
    params = {'name':b,'address1':a,'city':c, 'state':'Ca', 'country':'US'}
    url = "https://api.yelp.com/v3/businesses/"
    response = requests.get(url + i, headers=headers, params=params)
    response_json = response.json()
    ratings = response_json["rating"]
    reviews = response_json["review_count"]
    phones = response_json["display_phone"]
    cit = response_json["location"]["city"]
    t5_citi.append(cit)
    t5_phone.append(phones)
    t5_review.append(reviews)
    t5_rating.append(ratings)

printing Pizza Port Carlsbad || 0 of 152
printing AleSmith Brewing Co. || 1 of 152
printing The Lost Abbey || 2 of 152
printing Pizza Port Solana Beach || 3 of 152
printing Pizza Port Ocean Beach || 4 of 152

In [10]:
len(t5_rating)

5

In [11]:
yelp_brew_dict = {"Name":name, "Review Count":review, "Rating":rating}
yelp_brew_df = pd.DataFrame(yelp_brew_dict)
yelp_brew_df["Lat"] = lat
yelp_brew_df["lng"] = lng
yelp_brew_df["Phone#"] = phone
yelp_brew_df["City"] = citi
yelp_brew_df["Address"] = address
#_______________________________
top5["T5 Ratings"]= t5_rating
top5["T5 Review"]= t5_review
top5["T5 Phone"]= t5_phone
top5["T5 City"]= t5_citi
top5["T5 Lat"]= t5_lat
top5["T5 Lng"]= t5_lng
top5["T5 Address"] = t5_address
top5["T5 Name"] = t5_name

In [12]:
lat_list = yelp_brew_df["Lat"].tolist()
lng_list = yelp_brew_df["lng"].tolist()
rat_list = yelp_brew_df["Rating"].astype(float)
coordinates = list(zip(lat_list, lng_list))
locations = yelp_brew_df[["Lat", "lng"]].astype(float)
brew_name = yelp_brew_df["Name"].tolist()
review_ct = yelp_brew_df["Review Count"].tolist()
phone_lst = yelp_brew_df["Phone#"].tolist()
addy_lst = yelp_brew_df["Address"].tolist()
citi_lst = yelp_brew_df["City"].tolist()
#_______________________________________________________
t5_lat_list = top5["T5 Lat"].tolist()
t5_lng_list = top5["T5 Lng"].tolist()
t5_coordinates = list(zip(t5_lat_list, t5_lng_list))
t5_locations = top5[["T5 Lat", "T5 Lng"]].astype(float)
t5_brew_name = top5["T5 Name"].tolist()
t5_review_ct = top5["T5 Review"].tolist()
t5_phone_lst = top5["T5 Phone"].tolist()
t5_addy_lst = top5["T5 Address"].tolist()
t5_citi_lst = top5["T5 City"].tolist()
t5_rat_list = top5["T5 Ratings"].astype(float)

In [13]:
locations
figure_layout = {'width': '900px',
                 'height': '500px',
                 'border': '1px solid black',
                 'padding': '1px',
                 'margin': '0 auto 0 auto',
                 'Bold':True
                }
fig = gmaps.figure(layout=figure_layout)
markers = gmaps.marker_layer(coordinates, 
                             hover_text=[f"{brew} \n Rating: {rating}\n Reviews: {rev}\n Phone: {ph}\n Address: {add}, {cit}, CA " for brew, rating, rev, ph, add, cit in zip(brew_name, rat_list, review_ct, phone_lst, addy_lst, citi_lst)], 
                             label="", 
                             info_box_content=[f"Brewery Rating: {rating}" for rating in rat_list], 
                             display_info_box=None
                            )
                                
fig.add_layer(markers)

#_____________________________


#__________________________________

In [14]:
t5_layer = gmaps.symbol_layer(t5_coordinates, 
                              fill_color='yellow', 
                              stroke_color='red', scale=7,hover_text="", info_box_content="TOP5", display_info_box=None
                             )


fig = gmaps.figure()
fig.add_layer(t5_layer)

In [15]:
# Run this live

fig = gmaps.figure()

fig.add_layer(markers)
fig.add_layer(t5_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [ ]:
# for b, a, c, i, in zip(biz, addy, cities, ids):
# headers = {'Authorization': 'Bearer %s' % api_key}
# params = {'name':"10 Barrel Brewing Co",'address1':"501 E St",'city':"San Diego", 'state':'Ca', 'country':'US'}
# url = "https://api.yelp.com/v3/businesses/"
# response = requests.get(url + "8nEOrZJXEPbB7omJwyM1JQ", headers=headers, params=params)
# response_json = response.json()
# response_json

In [ ]:
# top5["T5 Ratings"]= t5_rating
# top5["T5 Review"]= t5_review
# top5["T5 Phone"]= t5_phone
# top5["T5 City"]= t5_citi
# top5["T5 Lat"]= t5_lat
# top5["T5 Lng"]= t5_lng
# top5

In [ ]:
# for i, row in yelp_brew_df.iterrows():
#     name = row['Name']
#     Lat = row['Lat']